# This is the project specific Settings.yml file.
# Place Sphinx specific build information here.
# Settings given here will replace the settings of 'conf.py'.

---
conf.py:
  copyright: 2018
  project: TYPO3 Themes - Modular Admin (Deutsch)
  version: 0.9
  release: 0.9.5
  latex_documents:
  - - Index
    - t3themes_modular_admin.tex
    - TYPO3 Themes - Modular Admin
    - Salvatore Eckel
    - manual
  latex_elements:
    papersize: a4paper
    pointsize: 10pt
    preamble: \usepackage{typo3}
...
